"""The C backend: portable source, every register a local.

READ THIS FIRST IF YOU ARE WRITING A BACKEND.

This is a complete, correct backend in about two hundred lines, and it is
deliberately the dumbest one that works. Every virtual register becomes a local
variable; there is no register allocation, no liveness, no instruction
selection. It emits C because a C compiler then handles the parts that are
genuinely hard and genuinely uninteresting -- calling conventions, stack
frames, relocation -- so this file can show only the part you actually have to
understand: how to walk the IR.

The shape below is the shape of every backend:

    for each function
        emit a prologue                     declare the registers
        for each block
            emit a label
            for each instruction
                switch on ins.op            <- the whole job
        emit an epilogue

A machine backend replaces "declare a C local" with "assign a stack slot or a
register" and "emit a C expression" with "emit an instruction". The traversal
never changes.

WHAT THIS BACKEND DOES NOT DO, ON PURPOSE
-----------------------------------------
It never allocates a register. Giving every value its own slot is always
correct; allocation is an optimisation, and `ir.regalloc` is there when you
want it. Starting with allocation is how a backend ends up subtly wrong in
ways that only appear under register pressure, which is exactly the hardest
case to debug.
"""
from __future__ import annotations

from ...ir import types as T
from ...backend.base import Backend, register
from ...ir.module import Function, Instruction, Module
from ...ir.opcodes import Op

#: IR type -> C type. `ptr` is an integer so pointer arithmetic needs no casts;
#: `i1` is 8-bit because that is how the IR stores it.
_CTYPE = {
    T.I1: "int8_t", T.I8: "int8_t", T.I16: "int16_t",
    T.I32: "int32_t", T.I64: "int64_t",
    T.U8: "uint8_t", T.U16: "uint16_t", T.U32: "uint32_t", T.U64: "uint64_t",
    T.F32: "float", T.F64: "double",
    T.PTR: "uintptr_t", T.VOID: "void",
}

_BIN = {
    Op.ADD: "+", Op.SUB: "-", Op.MUL: "*", Op.DIV: "/", Op.REM: "%",
    Op.AND: "&", Op.OR: "|", Op.XOR: "^", Op.SHL: "<<", Op.SHR: ">>",
    Op.EQ: "==", Op.NE: "!=", Op.LT: "<", Op.LE: "<=", Op.GT: ">", Op.GE: ">=",
}

_PRELUDE_TEMPLATE = """\
/* Generated by the `naive` backend. Compile with any C99 compiler. */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
/* For the host services this backend declares -- see `objects/hostsvc.py`.
   ONLY THESE TWO, and that is a hard-won constraint rather than minimalism.
   `<sys/stat.h>` and `<direct.h>` both drag in `<io.h>` on MinGW, which
   declares `_open`, `_read`, `_write` and `_close` -- exactly the names a
   `ctypes` program declares for itself, and two prototypes for one symbol do
   not compile. Adding them here re-created, from the other side, the obstacle
   `cffi.py` documents and this layer exists to retire. So the host services
   declare the handful of platform functions they need themselves; see
   `objects/hostsvc.py`. */
#include <errno.h>
#include <time.h>

/* The host functions the IR may call. A frontend emits calls to these by
   name; a real target would resolve them from a runtime library. */
@HOST@
@HOSTSVC@
static int  putchar_(int64_t c) { return putchar((int)c); }

@OBJECTS@
"""

# The runtime owns the host functions; this backend inlines them because its
# output is self-contained. Importing rather than repeating is what stops the
# two from drifting -- see `objects.support.HOST_FUNCTIONS`. A `static` function
# nothing calls draws a warning from some compilers, so the emitter drops the
# ones a given module never mentions.
from ...objects.csource import (  # noqa: E402
    OBJECT_NAMES as _OBJECT_NAMES, objects_c as _objects_c,
)
# The `apy_*` the C no longer defines because the IR does. See
# `objects/ir.py`; the prelude keeps a declaration for each so the
# runtime's own hundred-odd callers still have one in scope.
from ...objects.ir import (  # noqa: E402
    omitted_by as _omitted_by, split_by as _split_by,
)
from ...objects.support import (  # noqa: E402
    HOST_NAMES as _HOST_NAMES, host_functions as _host_functions,
)
from ...objects import hostsvc as _hostsvc  # noqa: E402

#: WHAT THIS BACKEND CAN DO FOR A PROGRAM, beyond the floor. It emits C and
#: links against a hosted libc, so it has a filesystem, a clock, entropy, an
#: environment, a dynamic loader, a network and threads. Only `text` is
#: missing, and
#: it would need the Unicode table wired to these names -- an honest absence,
#: and a program that needs it is refused by `Backend.check_host_services`
#: naming the group.
#:
#: `dynlib` IS THE RUN-TIME HALF OF `ctypes`, not a replacement for it: a
#: literal `CDLL("m")` is still a promise to the linker and still needs
#: nothing here. See the group's own commentary in `objects/hostsvc.py`.
#:
#: `net` IS WINSOCK ON WINDOWS, a library of its own where BSD sockets are
#: libc everywhere else -- and it is LOADED, not linked, so no group asks the
#: link step for anything. This said a function beside the group named the
#: link input; no such function was ever written, and every Windows build
#: failed to link for want of it. The group's own commentary says why loading
#: it is the better answer.
_HOSTSVC_GROUPS = frozenset({"file", "time", "random", "env", "dynlib",
                             "net", "proc", "thread"})

_HOST_C = _host_functions(static=True, strptr="uintptr_t", ptr="uintptr_t")

#: The host services this backend provides, as C. `static` and `uintptr_t` for
#: the same reason the host functions are: this backend inlines everything and
#: passes pointers as an integer.
_HOSTSVC_C = _hostsvc.c_source(_HOSTSVC_GROUPS, static=True, ptr="uintptr_t")


def _prelude(module) -> str:
    """The prelude for ONE module.

    Per-module rather than a constant because the object runtime's C omits
    exactly the definitions this module supplies in IR -- see
    `objects/ir.py`. A program with no spliced runtime keeps the C's,
    which is what stops a program that merely prints from carrying the
    ported code it never reaches.
    """
    return (_PRELUDE_TEMPLATE
            .replace("@HOST@", _HOST_C).replace("@HOSTSVC@", _HOSTSVC_C)
            .replace("@OBJECTS@",
                     _objects_c(static=True, omit=_omitted_by(module),
                                split=_split_by(module))))

#: Host functions defined by the prelude above. Any OTHER external the module
#: declares gets an `extern` declaration generated from its IR signature --
#: without one, C assumes `int f()`, and a call to a function returning double
#: reads the wrong register and produces a plausible wrong number instead of
#: any kind of error.
#:
#: Derived from the runtime's own list rather than repeated, so that adding a
#: host function in one place cannot leave this set behind -- a name missing
#: here gets BOTH an `extern` declaration and the prelude's `static` definition,
#: which is a C error about conflicting linkage.
#:
#: THE `_slow` HALVES COUNT TOO. A split function's C body is renamed
#: `apy_add_slow` and defined by the same prelude, but the name is not in the
#: runtime's own list -- that list is parsed from the C before the rename -- so
#: without this it gets an `extern` declaration beside a `static` definition,
#: which is the conflicting-linkage error this comment describes.
_PROVIDED = (set(_HOST_NAMES) | set(_OBJECT_NAMES) | {"putchar"}
             | {n + "_slow" for n in _OBJECT_NAMES})


class CBackend(Backend):
    name = "c"
    #: C99 source. Shared with `cpyext`, which is what makes
    #: `-o out.c` ambiguous and worth saying so.
    artifacts = (".c",)
    description = "portable C99 source; one local per register, no allocation"
    #: SOURCE IN ANOTHER LANGUAGE, so text is the artifact rather than a
    #: stage short of one. A C compiler does the encoding.
    kind = "language"
    default_target = "c"
    #: The emitted C defines its own `main` and its own host functions.
    self_contained = True
    #: See `_HOSTSVC_GROUPS` above for what these are and why `net` is not
    #: among them.
    host_services = _HOSTSVC_GROUPS
    #: WHAT THIS BACKEND MAKES IMPORTABLE. Reached as `import cinfo` -- and as
    #: `import c.cinfo`, which always works whether or not the bare name is
    #: free. `math` is here to demonstrate the collision rule and to be
    #: useful: the standard `math` wins the bare name, so `import math` is
    #: unchanged and `import c.math` reaches this one.
    modules = {
        "cinfo": {
            "name": ("str", "c"),
            "self_contained": ("int", 1),
            "word_bits": ("int", 64),
        },
        "math": {
            # The C library's own, which differ from the standard module's in
            # the one way that matters here: they are whatever the platform's
            # libm does, not what Python specifies.
            "sqrt": ("call", "apy_math_sqrt", 1),
            "libm": ("str", "platform"),
        },
    }

    def emit(self, module: Module, target) -> dict[str, bytes]:
        out: list[str] = [_prelude(module)]

        for g in module.globals:
            out.append(_global(g))
        if module.globals:
            out.append("")

        # Forward declarations, so call order in the module never matters.
        for f in module.functions:
            if f.external:
                if f.name not in _PROVIDED:
                    out.append("extern " + _signature(f) + ";")
            else:
                out.append(_signature(f) + ";")
        out.append("")

        for f in module.functions:
            if not f.external:
                out.append(self._func(f))
                out.append("")

        # An IR function called `main` is not C's `main`: C requires `int
        # main(void)` and the IR's may return i64 or take parameters. Emitting
        # it directly is a compile error, so it is renamed (see _cname) and a
        # real entry point wraps it. Without this the output looks correct and
        # fails at the C compiler, which is a confusing place to learn about it.
        #
        # THE WRAPPER TAKES THE COMMAND LINE AND HANDS IT ON, which is the
        # whole reason it takes any parameters at all: `main` is the one place
        # C offers a program its arguments, and `sys.argv` reads them back
        # through the `env` group's `host_arg_count`/`host_arg_get`. Those two
        # answered from statics nothing ever wrote until this line existed, so
        # every compiled program saw an empty command line -- see
        # `apy_host_args_take` in `objects/hostsvc.py`, whose own comment
        # named this wrapper before it did so.
        if module.function("main") is not None:
            out.append("int main(int argc, char **argv)")
            out.append("{")
            out.append("    apy_host_args_take(argc, argv);")
            out.append("    return (int)ir_main();")
            out.append("}")
            out.append("")

        return {"out.c": "\n".join(out).encode("utf-8")}

    # ── one function ────────────────────────────────────────────────────────
    def _func(self, fn: Function) -> str:
        L = [_signature(fn) + " {"]

        # Every register becomes a local. Declared up front and zeroed: a C
        # compiler warns about a "maybe uninitialised" local even where the IR
        # verifier has proved the read is safe, and the zeroing costs nothing
        # a C optimiser will not remove.
        for reg in sorted(fn.registers):
            if reg in fn.params:
                continue
            L.append(f"    {_CTYPE[fn.registers[reg]]} r{reg} = 0;")

        for blk in fn.blocks:
            L.append(f"{_label(blk.label)}:;")
            for ins in blk.instructions:
                L.append("    " + self._instr(fn, ins))

        L.append("}")
        return "\n".join(L)

    # ── one instruction: the whole job ──────────────────────────────────────
    def _instr(self, fn: Function, ins: Instruction) -> str:
        op, ty = ins.op, ins.ty
        d = f"r{ins.dst}"
        a = [f"r{x}" for x in ins.args]
        c = _CTYPE[ty]

        match op:
            case Op.CONST:
                return f"{d} = {_lit(ty, ins.imm)};"
            case Op.COPY:
                return f"{d} = {a[0]};"
            case Op.GLOBAL_ADDR:
                return f"{d} = (uintptr_t)g_{_cname(ins.sym)};"
            case Op.FUNC_ADDR:
                # THROUGH `_cname`, like the other two symbol sites. It was
                # the only one of the three that was not, and the reason it
                # survived is that nothing emitted this instruction until the
                # subset grew `funcaddr`: a Python program with a function
                # called `double`, `int` or `register` produced C that said
                # `&double` and did not compile. `GLOBAL_ADDR` and `CALL` next
                # to it were right all along, which is what made the omission
                # invisible to a reader checking the neighbours.
                return f"{d} = (uintptr_t)&{_cname(ins.sym)};"

            case Op.REM if ty.is_float:
                # C's `%` does not accept doubles at all, so this was a
                # compile error in the generated source rather than a wrong
                # answer -- the good version of this bug, and still one no
                # test had ever triggered.
                return (f"{d} = {'fmodf' if ty is T.F32 else 'fmod'}"
                        f"({a[0]}, {a[1]});")

            case Op.ADD | Op.SUB | Op.MUL | Op.DIV | Op.REM | Op.AND | Op.OR \
                 | Op.XOR | Op.SHL | Op.SHR:
                # The cast makes C's promotion rules match the IR's: without
                # it, `i8 + i8` is computed in `int` and does not wrap at 8
                # bits, so 127+1 would be 128 rather than -128.
                return f"{d} = ({c})(({c}){a[0]} {_BIN[op]} ({c}){a[1]});"
            case Op.NEG:
                return f"{d} = ({c})(-({c}){a[0]});"
            case Op.NOT:
                return f"{d} = ({c})(~({c}){a[0]});"

            case Op.EQ | Op.NE | Op.LT | Op.LE | Op.GT | Op.GE:
                return f"{d} = (({c}){a[0]} {_BIN[op]} ({c}){a[1]}) ? 1 : 0;"

            case Op.TRUNC | Op.EXTEND | Op.FTOI | Op.ITOF | Op.FTOF:
                return f"{d} = ({c}){a[0]};"
            case Op.BITCAST:
                src = _CTYPE[fn.register_type(ins.args[0])]
                return (f"memcpy(&{d}, &{a[0]}, "
                        f"sizeof({c}) < sizeof({src}) "
                        f"? sizeof({c}) : sizeof({src}));")

            case Op.ALLOCA:
                return f"{d} = (uintptr_t)alloca({ins.imm});"
            case Op.LOAD:
                return f"{d} = *({c} *){a[0]};"
            case Op.STORE:
                return f"*({c} *){a[1]} = ({c}){a[0]};"
            case Op.OFFSET:
                return f"{d} = {a[0]} + (uintptr_t){a[1]};"

            case Op.CALL:
                call = f"{_cname(ins.sym)}({', '.join(a)})"
                return f"{d} = {call};" if ins.dst is not None else f"{call};"
            case Op.CALL_PTR:
                args = ", ".join(a[1:])
                sig = f"{c} (*)({', '.join('int64_t' for _ in a[1:])})"
                call = f"(({sig}){a[0]})({args})"
                return f"{d} = {call};" if ins.dst is not None else f"{call};"

            case Op.JUMP:
                return f"goto {_label(ins.labels[0])};"
            case Op.BRANCH:
                return (f"if ({a[0]}) goto {_label(ins.labels[0])}; "
                        f"else goto {_label(ins.labels[1])};")
            case Op.SWITCH:
                arms = " ".join(
                    f"case {v}: goto {_label(l)};" for v, l in ins.cases)
                return (f"switch ({a[0]}) {{ {arms} "
                        f"default: goto {_label(ins.labels[0])}; }}")
            case Op.RET:
                return f"return {a[0]};" if ins.args else "return;"
            case Op.UNREACHABLE:
                return 'fprintf(stderr, "unreachable\\n"); abort();'

            case _:
                # Not a silent fallthrough. A new opcode must fail loudly here,
                # at build time, rather than emitting nothing and producing a
                # program that is wrong in a way no test names.
                raise NotImplementedError(
                    f"{self.name} backend has no rule for {op.value!r}"
                )


def _signature(fn: Function) -> str:
    params = ", ".join(
        f"{_CTYPE[fn.registers[p]]} r{p}" for p in fn.params) or "void"
    return f"{_CTYPE[fn.ret]} {_cname(fn.name)}({params})"


#: IR symbols that would collide with something C already defines. `main` is
#: renamed and wrapped (see emit); the rest are host functions whose C
#: signatures differ from the IR's.
_RESERVED = {"main": "ir_main", "putchar": "putchar_"}

#: C keywords and the standard type names. A source language has no reason to
#: avoid these -- `def double(n: int)` is perfectly good Python -- and emitting
#: the name verbatim produces `r7 = double(r1);`, which is a C syntax error
#: pointing at generated code the user never wrote. Everything here gets a
#: trailing underscore instead.
_C_KEYWORDS = frozenset("""
auto break case char const continue default do double else enum extern float
for goto if inline int long register restrict return short signed sizeof
static struct switch typedef union unsigned void volatile while
_Bool _Complex _Imaginary _Alignas _Alignof _Atomic _Generic _Noreturn
_Static_assert _Thread_local bool true false NULL
""".split())


def _label(name: str) -> str:
    """A C label for an IR block label.

    Block labels are frontend-chosen and hand-written IR is a documented way
    to test a backend, so nothing stops one being called `default` or
    `switch`. Prefixed rather than suffixed: a label is not a symbol anyone
    links against, so there is no reason to keep it recognisable to a linker,
    and a prefix cannot collide with a keyword at all.
    """
    return "L_" + _cname(name)


def _cname(name: str) -> str:
    """IR symbols may contain characters C does not allow in identifiers."""
    if name in _RESERVED:
        return _RESERVED[name]
    safe = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name)
    # Two different problems needing two different fixes. A keyword stops
    # being one with any suffix; a leading digit needs a PREFIX, and
    # suffixing `2fast` gives `2fast_`, which is still not an identifier.
    if safe and safe[0].isdigit():
        safe = "n" + safe
    if safe in _C_KEYWORDS:
        safe += "_"
    return safe


def _global(g) -> str:
    if g.data is None:
        return f"static uint8_t g_{_cname(g.name)}[{max(1, g.size)}];"
    body = ", ".join(str(b) for b in g.data)
    const = "const " if g.readonly else ""
    return (f"static {const}uint8_t g_{_cname(g.name)}[{len(g.data)}]"
            f" = {{{body}}};")


def _lit(ty: T.Type, v) -> str:
    if ty.is_float:
        f = float(v)
        # `repr` writes these as `inf` and `nan`, which are not C: `inf` is an
        # undeclared identifier and `nan` is the FUNCTION from math.h, so the
        # generated file failed to compile as soon as a program named
        # `math.inf`. The macros are C99 and math.h is already included.
        if f != f:
            return "(NAN)"
        if f - f != 0.0:
            return "(INFINITY)" if f > 0 else "(-INFINITY)"
        return repr(f)
    return f"INT64_C({int(v)})" if ty.size == 8 else str(int(v))


register(CBackend())
